# Generated by Django 2.2.7 on 2019-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0009_auto_20191205_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km_driven',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_year',
            field=models.CharField(choices=[('a', '2010'), ('b', '2011'), ('c', '2012'), ('d', '2013'), ('e', '2014'), ('f', '2015'), ('g', '2016'), ('h', '2017'), ('h', '2018'), ('h', '2019')], default='h', max_length=1),
        ),
    ]
