# Generated by Django 2.2.7 on 2019-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0010_auto_20191205_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km_driven',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='mil',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
    ]
