# Generated by Django 2.2.7 on 2019-12-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0011_auto_20191205_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_car_id', models.CharField(max_length=60)),
                ('liking_user', models.IntegerField()),
            ],
        ),
    ]
